### ISSUE TITLE
wrong sentence at https://vulkano.rs/guide/compute-pipeline

### ISSUE THREAD

**Issue by yvz5** [vulkano-rs/vulkano-www#11]
it says:

> Note: In the very far future it may be possible to write programs in Rust, or in a domain specific language that resembles Rust.

which basically nonsense. maybe you meant to write shader code directly in rust ?

**Comment by rukai** [comment]
Changed to:
``` Note: In the very far future it may be possible to write shaders in Rust, or in a domain specific language that resembles Rust.```
