### ISSUE TITLE
Separate the windowing section into unresizable and resizable.

### ISSUE THREAD

**Issue by CodesOtakuYT** [vulkano-rs/vulkano-www#126]
I think the windowing section would be more beginner-friendly if it started with an unresizable window, then a resizable window since handling resizability is much more complicated and involved.
Also, it makes more sense to transition from a PNG image to an unresizable surface as the windowing and swap chain stuff is already so complicated for a beginner.
Furthermore, not all users need a resizable window and the complexity that comes with it, especially video games.

**Comment by AustinJ235** [comment]
Closing as this repository is getting achieved. If you feel this is still a good idea, feel free to open an issue on the vulkano-book repository.
