### ISSUE TITLE
Paragraph on reusing pipelines is utterly mysterious

### ISSUE THREAD

**Issue by jimblandy** [vulkano-rs/vulkano-www#27]
I'm working my way through the Vulkano tutorial. It's going fine, but I can't figure out what this paragraph means at all:

> Note that you are allowed to use a set for a different pipeline than the one it was created with, but only if there is no conflict. However you can't create a descriptor set out of thin air, as Vulkan doesn't allow it.

I don't understand what sort of conflict there might be. I also don't see what is meant by "out of thin air". From what I understand at present, `PersistentDescriptorSet::start` creates a new `PersistentDescriptorSet` value; isn't that out of thin air?

It seems like this paragraph might be addressing questions an advanced user would have, and might be better to omit entirely from this part of the tutorial.

**Comment by jimblandy** [comment]
Perhaps what's meant (I'm guessing wildly here) is something like:

"Once you have created a descriptor set, you may also use it with other pipelines, as long as the bindings' types match up with those the pipelines' shaders expect. But Vulkan requires that you provide a pipeline whenever you create a descriptor set; you cannot create one independently of any particular pipeline."

**Comment by tomaka** [comment]
> Perhaps what's meant (I'm guessing wildly here) is something like:

Yes, that's exactly the meaning!
