### ISSUE TITLE
Guide sidebar should highlight current page

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano-www#35]
Guide sidebar should highlight current section, would make it easier to instantly see the context of the page you are on.

**Comment by adobrich** [comment]
Would you prefer a no JavaScript solution for this?

**Comment by rukai** [comment]
I would normally implement something like this server side e.g. https://github.com/rukai/pf_sandbox_infra/blob/9ccffaaed893810e7dcb27cb29afb809d9758dc6/website/templates/base.html.hbs#L28

However I have nothing against a javascript solution, and would merge a PR for one if it worked well.

**Comment by rukai** [comment]
Resolved by https://github.com/vulkano-rs/vulkano-www/pull/55
