### ISSUE TITLE
master branch is deployed instead of production branch

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano-www#58]
Despite configuring circleci to only deploy the production branch it deploys the master branch anyway.
https://github.com/vulkano-rs/vulkano-www/blob/master/.circleci/config.yml

No idea whats going wrong, even tried following a workaround with no success. As seen in the current `.circleci/config.yml`.

@tomaka any idea? This project is the only time I've dealt with circleci.

This is important so we can merge changes to the docs pertaining to unreleased changes in vulkano.

**Comment by tomaka** [comment]
I'm using clever-cloud for hosting. They are linked to github, they automatically detect changes in the repository and re-deploy. However it looks like they don't allow using a branch different from `master`.
