### ISSUE TITLE
Finishing the guide?

### ISSUE THREAD

**Issue by bwasty** [vulkano-rs/vulkano-www#59]
I see the guide is still pretty unfinished towards the end (http://vulkano.rs/guide/acquire-present). Do you think it would make sense to link to [vulkan-tutorial-rs](https://github.com/bwasty/vulkan-tutorial-rs) instead, specifically the sections about [Rendering and presentation](https://github.com/bwasty/vulkan-tutorial-rs#rendering-and-presentation) and [Swapchain recreation](https://github.com/bwasty/vulkan-tutorial-rs#swapchain-recreation)?

**Comment by hakolao** [comment]
Closing this due to the recently updated website being more up to date & better now.
