### ISSUE TITLE
Compute Operations code does not compile

### ISSUE THREAD

**Issue by kunalmohan** [vulkano-rs/vulkano-www#76]
I was going through the tutorial and found that the compute operations code does not compile. It throws the following error:
```
error[E0609]: no field `khr_storage_buffer_storage_class` on type `&vulkano::device::extensions::DeviceExtensions`
   --> src/main.rs:199:9
    |
199 | /         vulkano_shaders::shader!{
200 | |             ty: "compute",
201 | |             src: "
202 | | #version 450
...   |
210 | | }"
211 | |         }
    | |         ^ in this macro invocation
    | |_________|
    | 

error: aborting due to previous error
```

**Comment by sivese** [comment]
https://github.com/eisterman/vulkano-www/commit/e940dbe24df653be62ecfd86a36a7040092462a7 this will help you

**Comment by kunalmohan** [comment]
I got another error along with the previous one this time:
```
error[E0560]: struct `vulkano::device::extensions::DeviceExtensions` has no field named `khr_storage_buffer_storage_class`
   --> src/main.rs:187:31
    |
187 |             &DeviceExtensions{khr_storage_buffer_storage_class:true, ..DeviceExtensions::none()},
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `vulkano::device::extensions::DeviceExtensions` does not have this field
    |
    = note: available fields are: `khr_swapchain`, `khr_display_swapchain`, `khr_sampler_mirror_clamp_to_edge`, `khr_maintenance1`, `khr_get_memory_requirements2` ... and 4 others
```

**Comment by sivese** [comment]
did you add 'vulkano-shaders = "0.16.0"' dependency in cargo.toml ?

**Comment by kunalmohan** [comment]
Yes it's there in the cargo.toml

**Comment by eisterman** [comment]
What version of vulkano are you using?
Now at the v0.17 there isn't the device::extensions submodule, but DeviceExtension are directly in the vulkano::device module, so i'm thinking you're using an old version of the crate.

https://github.com/vulkano-rs/vulkano-www/pull/74 is a pull request i've maded some time ago for fix the website, but nobody have confirmed or commented the fix

**Comment by kunalmohan** [comment]
@eisterman Yes, I was using v0.13 as mentioned in the tutorial. Upgrading to v0.17 gives two different errors:
```
error[E0061]: this function takes 4 parameters but 3 parameters were supplied
   --> src/main.rs:195:23
    |
195 |       let data_buffer = CpuAccessibleBuffer::from_iter(device.clone(), BufferUsage::all(),
    |  _______________________^
196 | |                                                     data_iter).expect("failed to create buffer");
    | |______________________________________________________________^ expected 4 parameters

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
   --> src/main.rs:221:24
    |
221 |     let set = Arc::new(PersistentDescriptorSet::start(compute_pipeline.clone(), 0)
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter
```
I found that CpuAccessibleBuffer now accepts host_cached parameter, so I just passed a `true` value (though I am not sure what would be better). PersistentDescriptorSet accepts only Arc<UnsafeDescriptorSetLayout> as parameter, which I am not sure how to create from compute_pipeline.

Also, do you recommend to follow the tutorial using the latest version of vulkano? Or have there been major changes in the crate since the tutorial was written?

**Comment by eisterman** [comment]
There have been breaking changes in almost every version change.
Actually at the moment my advice is to use 0.16 and to follow the code of this pull request, which I had verified to work: https://github.com/eisterman/vulkano-www/tree/patch-1/examples

**Comment by kunalmohan** [comment]
Okay. Thanx!
