### ISSUE TITLE
Missing '&'

### ISSUE THREAD

**Issue by PortStone** [vulkano-rs/vulkano-www#79]
At: http://vulkano.rs/guide/graphics-pipeline-creation

![2020-04-13_23-55](https://user-images.githubusercontent.com/27790087/79164908-588df280-7de2-11ea-8fc8-fa9ea002417f.png)

should be &dynamic_state

**Comment by AustinJ235** [comment]
Closed via https://github.com/vulkano-rs/vulkano-www/pull/84
