### ISSUE TITLE
'Device extension "khr_storage_buffer_storage_class" required

### ISSUE THREAD

**Issue by 13ros27** [vulkano-rs/vulkano-www#87]
I am working through the guide and I ran into an issue at the end of 'dispatch' where I got `thread 'main' panicked at 'Device extension "khr_storage_buffer_storage_class" required', src\main.rs:36:9` which is coming from the `vulkano_shaders::shader!` line and I don't know how to fix it

**Comment by AustinJ235** [comment]
When you do Device::new you pass a DeviceExtentions struct you need to set that extension field to true.

**Comment by 13ros27** [comment]
Thanks that worked, I changed it to `DeviceExtensions::supported_by_device(physical)`, maybe something to mention in the tutorial?
