### ISSUE TITLE
Compute shader dispatch fails due to missing extension

### ISSUE THREAD

**Issue by willmtemple** [vulkano-rs/vulkano-www#88]
Working through [the guide page on dispatching a compute shader](https://vulkano.rs/guide/dispatch), I get a panic during shader loading due to missing device extension `khr_storage_buffer_storage_class`.

`thread 'main' panicked at 'Device extension "khr_storage_buffer_storage_class" required',`

It isn't too difficult to figure out what to do, but it's not mentioned in the guide that it (might?) be required to initialize the device with the extension:

```rust
    let (device, mut queues) = Device::new(
        physical,
        &Features::none(),
        &DeviceExtensions {
            khr_storage_buffer_storage_class: true,
            ..DeviceExtensions::none()
        },
        [(queue_family, 0.5)].iter().cloned(),
    )
    .expect("failed to create device");
```

**Comment by hakolao** [comment]
This `khr_storage_buffer_storage_class` is used in `compute_pipeline.rs` now, so this issue should be fixed. On my machine (Linux) this works without the extension also, so i'm not quite sure when it's needed, but the fix is straightforward :)
