### ISSUE TITLE
vulkano 0.19 build failure in empty project

### ISSUE THREAD

**Issue by cdwfs** [vulkano-rs/vulkano-www#90]
I'm on the [first page of the guide](https://vulkano.rs/guide/introduction) (which recommends installing vulkano 0.19), and just trying to build an empty main.rs with the crate installed gives me a build failure:
```
> Executing task: cargo build <

   Compiling vulkano v0.19.0
error[E0609]: no field `shaderf3264` on type `PhysicalDeviceFeatures`
   --> C:\Users\cdwfs\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.19.0\src\features.rs:459:28
    |
459 |     core { shader_f3264 => shaderf3264 },
    |                            ^^^^^^^^^^^ help: a field with a similar name exists: `shaderInt64`

error[E0308]: mismatched types
    --> C:\Users\cdwfs\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.19.0\src\command_buffer\sys.rs:1455:38     
     |
1455 |         vk.CmdSetBlendConstants(cmd, constants); // TODO: correct to pass array?
     |                                      ^^^^^^^^^
     |                                      |
     |                                      expected `&[f32; 4]`, found array `[f32; 4]`
     |                                      help: consider borrowing here: `&constants`

error: aborting due to 2 previous errors
```
I'm on Windows, with version 1.2.162.0 of the Vulkan SDK installed if that makes a difference. I see vulkano 0.20.0 is available, and changing to "vulkano = 0.20" in Crates.toml made the error go away, so it may be worth updating the guide to suggest version 0.20 instead.

**Comment by clay53** [comment]
Not just a Windows only issue btw. It also fails on Arch Linux. The latest 0.22 version works as well.

**Comment by Mg138** [comment]
Using Arch Linux, it seems that only version 0.21 compiles.

**Comment by hakolao** [comment]
Closing this, as this is likely outdated now.
