### ISSUE TITLE
Mandelbrot set example fails

### ISSUE THREAD

**Issue by XPCMasterX** [vulkano-rs/vulkano-www#93]
The guide says to do this when creating a descriptor set:
`
let layout = compute_pipeline.layout().descriptor_set_layout(0).unwrap();
let set = Arc::new(PersistentDescriptorSet::start(layout.clone())
    .add_image(image.clone()).unwrap()
    .build().unwrap()
);
`
But in the latest version, you need the following code:
`
use vulkano::image::view::ImageView;
let layout = compute_pipeline.layout().descriptor_set_layout(0).unwrap();
    let set = Arc::new(
        PersistentDescriptorSet::start(layout.clone())
            .add_image(ImageView::new(image.clone()).unwrap())
            .unwrap()
            .build()
            .unwrap(),
    );
`
Note the `add_image` part; you need to use `ImageView::new`.

**Comment by Eliah-Lakhin** [comment]
@XPCMasterX After the long delay, we have recently updated the website's tutorial. Is this issue still relevant?

**Comment by hakolao** [comment]
This should be up to date
