### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by post-rex** [vulkano-rs/vulkano-www#95]
The guide is incredibly outdated, and unfinished.
It is hard to get examples out of it working for newer versions and get started in general.

PLEASE either update and finish it, or add a disclaimer about the state.

**Comment by Eliah-Lakhin** [comment]
@post-rex We have recently updated the entire tutorial on the website, and are going to keep it up to date on a more regular basis. Would you mind to take a look and let us know if there are any issues? Thank you!

**Comment by hakolao** [comment]
I'd consider this issue closed now that the website is more up to date
